### ISSUE TITLE
First try

### ISSUE THREAD

**Issue by arakweker** [AppPear/ChartView#2]
Installed SwiftUICharts in the package manager in Xcode 11 beta 4. It is visible in the project navigator (Swift Package Dependencies).

I made a new SwiftUI file, called ChartView. 

`import SwiftUI
import SwiftUICharts

struct ChartView: View {
        
    var body: some View {
        
        ChartView(data: [12,17,24,33,23,56], title: "Chart two", form: Form.small)    }

}

#if DEBUG
struct ChartView_Previews: PreviewProvider {
    static var previews: some View {
        ChartView()
    }
}
#endif
`

Now I'm getting an error "Argument passed to call that takes no arguments".

**Comment by AppPear** [comment]
Sorry, but I couldn't reproduce this issue. It worked without errors for me. I'm using the latest (beta 4 Xcode)
Here is my code: 

``` swift
import SwiftUI
import SwiftUICharts

struct ContentView: View {
    var body: some View {
         ChartView(data: [12,17,24,33,23,56], title: "Chart two", form: Form.small)
    }
}

#if DEBUG
struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
#endif
```

**Comment by kimbauters** [comment]
This is indeed a bug. The problem with a declarative framework such as SwiftUI is that debugging is really hard and often errors pop up in the weirdest of places. That being said, after reading the code line by line I found that the problem is with the struct named "Form" in ChartView. This conflicts with the built-in Form used in SwiftUI, so you get the bug in projects using Form. Simply renaming Form to ChartSize or something similar resolves the issue.

**Comment by AppPear** [comment]
Thanks I'll do a renaming then
